spring.application.name=MovoBackend

# --- CONFIGURACION DEL SERVIDOR ---
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# --- CONFIGURACION DE LA BASE DE DATOS (POSTGRESQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/movodb
spring.datasource.username=movo
spring.datasource.password=movopassword
spring.datasource.driver-class-name=org.postgresql.Driver

# --- CONFIGURACION DE JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true